language: node_js
node_js: node
before_script:
- npm install -g gitbook-cli
script:
- gitbook install
- gitbook build
deploy:
  local_dir: _book
  provider: pages
  skip_cleanup: true
  name: Travis Build Bot
  keep_history: true
  on:
    branch: master
  target_branch: gh-pages
  # github_token:
    # secure: G7TvG2mnukAWmtlmvJaeRdiKhZYcdR4jrh2gCcY/88wv8dLpzD5ys18ePWKs4DkOHDd0CQ8ZsxxFZ2nek1qB3UsC1wIR2Cy5ABuyNhqvTMauXIzzrmFh5r4bbbdks0eJGwB/iEOU2bkZq412xx2PCarq03V7brNlAM03lqut/s5JPFlPgdBaHidj8U2bL97AStKDYtQOJyxN3SQY2ti/k59ahby67ZNWZlReFC5E/HL3vqL6Va5x4AiLQQAvJfogV9geNkrUjgcn5z5+nVD+bc5FxT3wBBngxUiT1q9cZfLtsgG1+pbT6DHqNLNAui99HRopsjT1IkbJ/TOsNO9QrZvwwH2eOynq5cNYi7j6iGdb+0GHqoMybzkfu/TGIajbh0wDuY/q/4D8rzVcpq1LASHCbZsidyMrMu0J3vVDFZwfyUv/Ez14LWgcNRoQtiUtV5NaSXYZYTIQ6gsz6vKosc9KpkV3HX63KFCjeOy4rNNmi4ys9z0Ct2lzfh3+R6US7d7qJd44EfG2tVEJCZLFWlisU4NMWc9oV51KDlIX4zmQ6aDpL1NtAz7LfqDL+7VoOAAAruCkvpIx49tErWYxZM6BUQrNUCrAIhnKD1Kde6rSxKMWaj8DAEXyK1qU74diaMzTkA9idPyHAV1jY+4EXPOcamm91gRpMltGYvOS+Ik=
env:
  global:
    secure: gNie4Y+sXvtj0XmdgjMQ/XVctZICjqvRxkZZeHYTH7samtDEOidLWGesriJNLpquEptAPAPerTiAK6Uy7gW9PM4YcI/tDReIB2+yRI+r/EPGD/FMijO9tqNIReiS0IrQgQ8pq4DNSsJ2wbcMkwOHk9b1RvQhnyZ8uYoFRrzrZe5VAn2MH/H3ytxKoh8TXuNk14ZaZtc5y0lbAahUKdsPgSpEjfyqMTmWT7CaXUq0HC9OChbwz/jp1iUM99/FxTc4jmRwnF1uFgpqZKMxu2XV0DC1z2w6132PPPn4TZ97diWfYzOx8U/0Yyla55GyQqcoHrqDcWHwZW8uZYnnxJ6m7XR8YGUK9hkMYrSUMmtEbpIi5D7RuXt8erFNm2LjiK7QhcfNmp0YzwsmbRD6obBv+ioPD2PvcaPiJ9r4M3ODUdKJa7ei83/U8xqydyJ4OAUzYw52aFwyIcopQD52yYf2inmgG4G6p0ozi8smeF7zp/s2vC/UhSavCKDHyERC3UOPV0JTEZMtwUSnTm/qNwZPM3CVQu53yHp/oZB0wXAiSYktQMoNcLiEtimYfh0035QoyewIjcIMgKD9WeN4W88LqgVuSJB+hGF5iNFHJuxCfEwtqcn5l9UodAuKj0DzeQzxYL9/ACaGy+JtJOEkED6I2021yKqaeeWVHsXFWaAOWjM=
